# Persistent storage — S3 bucket for encrypted file objects and DynamoDB table
# for file metadata. S3 holds the raw AES-GCM encrypted bytes uploaded via
# presigned URL; DynamoDB holds the share ID, S3 key, and expiry timestamp.
# Public access is fully blocked — clients reach S3 only through short-lived
# presigned URLs generated by the Lambda functions. The lifecycle rule deletes
# objects after 24 hours as a fallback; DynamoDB conditional delete is the
# primary one-time-access gate. DynamoDB TTL handles metadata expiry but can
# lag up to 48 hours — the view Lambda checks expiresAt explicitly.

resource "aws_s3_bucket" "files" {
  bucket = "${var.env}-filedeadrop-files"
}

resource "aws_s3_bucket_public_access_block" "files" {
  bucket = aws_s3_bucket.files.id

  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}

resource "aws_s3_bucket_cors_configuration" "files" {
  bucket = aws_s3_bucket.files.id

  cors_rule {
    allowed_origins = var.frontend_origins
    allowed_methods = ["PUT", "GET"]
    allowed_headers = ["*"]
    expose_headers  = ["ETag"]
    max_age_seconds = 3000
  }
}

resource "aws_s3_bucket_lifecycle_configuration" "files" {
  bucket = aws_s3_bucket.files.id

  rule {
    id     = "expire-after-24h"
    status = "Enabled"

    filter {}

    expiration {
      days = 1
    }
  }
}

resource "aws_s3_bucket_server_side_encryption_configuration" "files" {
  bucket = aws_s3_bucket.files.id

  rule {
    apply_server_side_encryption_by_default {
      sse_algorithm = "AES256"
    }
  }
}

resource "aws_dynamodb_table" "metadata" {
  name         = "${var.env}-filedeadrop-metadata"
  billing_mode = "PAY_PER_REQUEST"
  hash_key     = "documentId"
  range_key    = "itemType"

  attribute {
    name = "documentId"
    type = "S"
  }

  attribute {
    name = "itemType"
    type = "S"
  }

  ttl {
    attribute_name = "expiresAt"
    enabled        = true
  }

  server_side_encryption {
    enabled = true
  }
}
