import styles from './PrivacyPolicy.module.css'

export default function PrivacyPolicy() {
  return (
    <main>
      <h1>Privacy Policy</h1>
      <span className={styles.updated}>Last updated: July 1, 2026</span>

      <p className={styles.lead}>
        filedeadrop is a one-time, end-to-end encrypted file sharing service. This policy explains
        what information is collected when you use filedeadrop.com, how it is used, how long it is
        retained, and your rights with respect to it.
      </p>
      <p className={styles.lead}>
        The short version: your files are encrypted in your browser before upload, the encryption
        key never reaches any server, and the file is permanently deleted after the first access or
        24 hours — whichever comes first. The only personal data collected is standard server
        request metadata (IP address and user agent), retained for 30 days for security and
        operational purposes. If you optionally request a receipt link at upload, a small status
        record — no filename, file contents, or IP address — is kept separately for up to 48 hours
        so you can confirm whether the file was received.
      </p>

      <hr />

      <section className={styles.section}>
        <h2 className={styles.heading}>1. Who operates this service</h2>
        <p className={styles.body}>
          filedeadrop is an independent personal project. There is no corporate entity. For
          privacy-related inquiries, contact:{' '}
          <a href="mailto:mikepdxrider@gmail.com">mikepdxrider@gmail.com</a>
        </p>
      </section>

      <hr />

      <section className={styles.section}>
        <h2 className={styles.heading}>2. What data is collected</h2>

        <p className={styles.sublabel}>2a. Data you provide</p>
        <p className={styles.body}>
          filedeadrop does not require an account, registration, or any personal information to use.
          No name, email address, or identifying information is ever collected.
        </p>
        <p className={styles.body}>
          When you upload a file, the following occurs entirely in your browser before anything is
          transmitted:
        </p>
        <ul className={styles.list}>
          <li>
            A one-time AES-GCM-128 encryption key is generated by your browser using the Web Crypto
            API.
          </li>
          <li>
            Your file and its filename are encrypted client-side. The encryption key is never
            transmitted to any server.
          </li>
          <li>
            Only the encrypted file bytes are uploaded — directly to Amazon S3 via a presigned URL.
            The application server never receives your file's contents.
          </li>
          <li>
            The encryption key, encrypted filename, and file identifier are embedded in the share
            link in the URL fragment (the <code>#</code> portion). URL fragments are never
            transmitted by browsers in HTTP requests and therefore never appear in any server log.
          </li>
        </ul>

        <p className={styles.sublabel}>2b. Optional receipt tracking data</p>
        <p className={styles.body}>
          If you check "Get a link to track when it's viewed" at upload, a second record is created
          containing:
        </p>
        <ul className={styles.list}>
          <li>
            A separate, randomly generated receipt token — not derivable from the share link, and
            never given to your recipient.
          </li>
          <li>
            The upload time, and (if applicable) the time the file was accessed and the time it was
            deleted.
          </li>
          <li>A status: pending, accessed, or expired.</li>
        </ul>
        <p className={styles.body}>
          This record never contains the filename, file contents, IP address, or any other
          identifying information. It exists only if you opt in, and is automatically deleted 48
          hours after upload regardless of the file's own expiry.
        </p>

        <p className={styles.sublabel}>2c. Data collected automatically</p>
        <p className={styles.body}>
          Every request to the filedeadrop API generates a structured access log entry in Amazon
          CloudWatch. Each entry contains:
        </p>
        <div className={styles.tableWrap}>
          <table className={styles.table}>
            <thead>
              <tr>
                <th>Field</th>
                <th>Description</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>IP address</td>
                <td>The originating IP of the request</td>
              </tr>
              <tr>
                <td>User agent</td>
                <td>Browser and operating system string</td>
              </tr>
              <tr>
                <td>Request ID</td>
                <td>An AWS-generated identifier, not linked to you</td>
              </tr>
              <tr>
                <td>Route</td>
                <td>
                  The route template (e.g. <code>GET /view/&#123;id&#125;</code>) — not the
                  resolved file ID
                </td>
              </tr>
              <tr>
                <td>Status code</td>
                <td>HTTP response code</td>
              </tr>
              <tr>
                <td>Response length and latency</td>
                <td>Request performance metrics</td>
              </tr>
              <tr>
                <td>Error message</td>
                <td>Populated only on failed requests</td>
              </tr>
            </tbody>
          </table>
        </div>
        <p className={styles.body}>
          <strong>What is not logged:</strong> the encryption key (it never leaves your browser),
          the resolved file identifier on successful requests, file contents, and filenames.
        </p>

        <p className={styles.sublabel}>2d. What is not collected</p>
        <ul className={styles.list}>
          <li>Cookies — none are set.</li>
          <li>Session data — there are no sessions.</li>
          <li>Analytics or tracking scripts — none are present on the site.</li>
          <li>
            Third-party fonts or external resources — all assets are self-hosted and served from
            filedeadrop's own infrastructure.
          </li>
        </ul>
      </section>

      <hr />

      <section className={styles.section}>
        <h2 className={styles.heading}>3. How data is used</h2>
        <p className={styles.body}>
          Automatically collected request metadata (IP address and user agent) is used solely for:
        </p>
        <ul className={styles.list}>
          <li>Security monitoring and abuse prevention</li>
          <li>Diagnosing operational errors</li>
          <li>Understanding aggregate traffic patterns</li>
        </ul>
        <p className={styles.body}>
          This data is not used for advertising, profiling, or sale to third parties under any
          circumstances.
        </p>
      </section>

      <hr />

      <section className={styles.section}>
        <h2 className={styles.heading}>4. Data retention</h2>
        <div className={styles.tableWrap}>
          <table className={styles.table}>
            <thead>
              <tr>
                <th>Data type</th>
                <th>Retention period</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>Encrypted file (S3)</td>
                <td>Deleted on first access, or after 24 hours — whichever comes first</td>
              </tr>
              <tr>
                <td>File record (DynamoDB)</td>
                <td>Deleted atomically on first access</td>
              </tr>
              <tr>
                <td>Receipt record (DynamoDB, opt-in only)</td>
                <td>48 hours from upload, then automatically deleted</td>
              </tr>
              <tr>
                <td>API access logs (CloudWatch)</td>
                <td>30 days</td>
              </tr>
              <tr>
                <td>Lambda execution logs (CloudWatch)</td>
                <td>30 days</td>
              </tr>
            </tbody>
          </table>
        </div>
        <p className={styles.body}>
          After the file is deleted from S3 and DynamoDB, it cannot be recovered. There is no
          backup.
        </p>
      </section>

      <hr />

      <section className={styles.section}>
        <h2 className={styles.heading}>5. Data storage and regional residency</h2>
        <p className={styles.body}>
          filedeadrop is hosted on Amazon Web Services (AWS). At upload time, you choose a storage
          region:
        </p>
        <ul className={styles.list}>
          <li>
            <strong>US uploads</strong> are stored and processed in AWS us-west-2 (Oregon).
          </li>
          <li>
            <strong>EU uploads</strong> are stored and processed in AWS eu-central-1 (Frankfurt,
            Germany).
          </li>
        </ul>
        <p className={styles.body}>
          Server access logs are written to CloudWatch in the same region as the upload. EU users'
          IP addresses and request metadata are logged in Frankfurt and do not leave the EU region.
        </p>
        <p className={styles.body}>
          AWS is the sole infrastructure sub-processor. AWS processes data under its own terms of
          service and data processing agreements. For more information, see{' '}
          <a href="https://aws.amazon.com/privacy/" target="_blank" rel="noopener noreferrer">
            aws.amazon.com/privacy
          </a>
          .
        </p>
      </section>

      <hr />

      <section className={styles.section}>
        <h2 className={styles.heading}>6. Data sharing</h2>
        <p className={styles.body}>
          No personal data is sold, rented, or shared with third parties for marketing or any
          commercial purpose.
        </p>
        <p className={styles.body}>
          Data may be disclosed if required by law, court order, or valid legal process directed at
          the operator. Given the 30-day log retention and the architecture described above, the
          data available to disclose is limited to IP addresses, user agents, and request timestamps
          within that window. File contents and encryption keys are never available to disclose —
          the service is technically incapable of accessing them.
        </p>
        <p className={styles.body}>
          For uploads where a receipt was requested, the same legal process could additionally
          surface the receipt's status and timestamps — never the file's contents, filename, or
          encryption key.
        </p>
      </section>

      <hr />

      <section className={styles.section}>
        <h2 className={styles.heading}>7. Security</h2>
        <p className={styles.body}>
          Files are encrypted with AES-GCM-128 before leaving your device. The encryption key
          exists only in the share link's URL fragment, which browsers do not transmit in HTTP
          requests. This means the key is never held by filedeadrop's servers, never appears in any
          log, and is unrecoverable without the share link. Anyone with the share link can access
          the file exactly once.
        </p>
        <p className={styles.body}>
          You are responsible for protecting the share link. Once a file has been accessed, it is
          permanently deleted and cannot be retrieved.
        </p>
      </section>

      <hr />

      <section className={styles.section}>
        <h2 className={styles.heading}>8. File size limit</h2>
        <p className={styles.body}>
          Files are limited to 250 MB. This limit is enforced at the API layer before a presigned
          upload URL is issued.
        </p>
      </section>

      <hr />

      <section className={styles.section}>
        <h2 className={styles.heading}>9. Children's privacy</h2>
        <p className={styles.body}>
          filedeadrop is not directed at children under the age of 13 and does not knowingly
          collect personal information from children under 13. If you are under 13, do not use this
          service. If you believe a child under 13 has used this service, contact{' '}
          <a href="mailto:mikepdxrider@gmail.com">mikepdxrider@gmail.com</a> and any associated
          request logs will be deleted to the extent they can be identified.
        </p>
      </section>

      <hr />

      <section className={styles.section}>
        <h2 className={styles.heading}>10. Your rights</h2>
        <p className={styles.body}>
          Because filedeadrop does not collect accounts or persistent personal identifiers, most
          conventional data subject rights (access, correction, portability) are not practically
          applicable — there is no profile to retrieve or correct.
        </p>
        <p className={styles.body}>With respect to request logs:</p>
        <ul className={styles.list}>
          <li>Logs are automatically deleted after 30 days.</li>
          <li>
            If you have a specific concern about logged data associated with a known IP address or
            time window, you may contact{' '}
            <a href="mailto:mikepdxrider@gmail.com">mikepdxrider@gmail.com</a> to request
            deletion. Requests will be honored to the extent technically feasible.
          </li>
        </ul>
      </section>

      <hr />

      <section className={styles.section}>
        <h2 className={styles.heading}>11. Changes to this policy</h2>
        <p className={styles.body}>
          If this policy is materially updated, the "Last updated" date at the top of this page
          will be revised. Continued use of the service after a change constitutes acceptance of
          the revised policy.
        </p>
      </section>

      <hr />

      <section className={styles.section}>
        <h2 className={styles.heading}>12. Contact</h2>
        <p className={styles.body}>
          For any privacy-related questions or requests:{' '}
          <a href="mailto:mikepdxrider@gmail.com">mikepdxrider@gmail.com</a>
        </p>
      </section>
    </main>
  )
}
