name: Deploy Terraform

on:
  push:
    branches: [dev, main]
    paths:
      - 'terraform/**'
      - 'api/lambda/**'

permissions:
  id-token: write   # required for OIDC
  contents: read

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

concurrency:
  group: terraform-apply-${{ github.ref_name }}
  cancel-in-progress: false

jobs:
  deploy-dev:
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    environment: dev

    defaults:
      run:
        working-directory: terraform/environments/dev

    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.TF_AWS_ROLE_ARN }}
          aws-region: us-west-2

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "~> 1.14"

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve
        env:
          TF_VAR_route53_zone_id: ${{ secrets.TF_VAR_ROUTE53_ZONE_ID }}
          TF_VAR_dev_api_key: ${{ secrets.TF_VAR_DEV_API_KEY }}

  deploy-prod:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        working-directory: terraform/environments/prod

    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.TF_AWS_ROLE_ARN }}
          aws-region: us-west-2

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "~> 1.14"

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve
        env:
          TF_VAR_route53_zone_id: ${{ secrets.TF_VAR_ROUTE53_ZONE_ID }}
